### ISSUE TITLE
Ccan

### ISSUE THREAD

**Issue by AIRS-EXR** [AdaRoseCannon/aframe-ar-boilerplate#1]

**Comment by AIRS-EXR** [comment]
can not open in Quest 1(Browser version 16.3), could u please tell me how to fix it? and it seems all the API from aframe is unable to use?(like https://github.com/marlon360/webxr-handtracking)

**Comment by AdaRoseCannon** [comment]
That particular demo looks pretty old, the hand tracking API changed since then so that demo may need to be updated.

Try this example instead: https://aframe.io/examples/showcase/handtracking/
